[workspace]

members = [
    "tailcall",
    "tailcall-impl",
]

[workspace.package]
description = "Safe, zero-cost tail recursion"
documentation = "https://docs.rs/tailcall"
repository = "https://github.com/alecdotninja/tailcall"
readme = "README.md"
keywords = ["recursion", "tail", "tailcall", "become"]
categories = ["algorithms", "no-std"]
license = "MIT OR Apache-2.0"
authors = ["Alec Larsen <hello@alec.ninja>"]
version = "1.0.0"
edition = "2018"