[package]
name = "tailcall"
description = "Safe, zero-cost tail recursion"
documentation = "https://docs.rs/tailcall"
repository = "https://github.com/alecdotninja/tailcall"
readme = "README.md"
keywords = ["recursion", "tail", "tailcall", "become"]
categories = ["algorithms", "no-std"]
exclude = ["/.travis.yml", ".gitignore"]
license = "MIT OR Apache-2.0"
authors = ["Alec Larsen <hello@alec.ninja>"]
version = "0.1.4"
edition = "2018"

[badges]
travis-ci = { repository = "alecdotninja/tailcall" }

[dependencies]
tailcall-impl = { path = "impl", version = "0.1.4" }

[dev-dependencies]
backtrace = "0.3.40"
