[package]
name = "tailcall"
description.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
tailcall-impl = { path = "../tailcall-impl" }

[dev-dependencies]
backtrace = "~0.3"
bencher = "~0.1"

[[bench]]
name = "bench"
harness = false
